import { defineCollection } from "astro:content";
// `z` re-exported from `astro:content` is deprecated; import it from
// `astro/zod` (the pattern nimbus-docs' own schema helpers document).
import { z } from "astro/zod";
import { docsCollection, partialsCollection } from "@cloudflare/nimbus-docs/content";

export const collections = {
  docs: defineCollection(
    docsCollection({
      schemaFields: {
        // Nimbus docs are agent-friendly by default. Set `audience: human`
        // to flag a page that's written primarily for human readers.
        audience: z.literal("human").optional(),
        // Set by the sync script on English-tree pages that fall back to the
        // Chinese source. The root route renders these with the "not
        // translated yet" banner.
        untranslated: z.boolean().optional(),
      },
    }),
  ),
  // Chinese mirror of the docs, mounted at `/zh/**` via Nimbus's
  // `versions.others` mechanism (see `astro.config.ts`). Hand-translated user
  // docs live in `src/content/docs-zh/docs/`; `src/content/docs-zh/dev/**` is
  // generated by `scripts/sync-docs.mjs` from the Chinese dev tree.
  "docs-zh": defineCollection(
    docsCollection({
      base: "docs-zh",
      schemaFields: {
        audience: z.literal("human").optional(),
        // Mirror of `docs`: set on a `/zh` page that only exists in English
        // (rare). The `/zh` route renders these with the Chinese notice.
        untranslated: z.boolean().optional(),
      },
    }),
  ),
  changelog: defineCollection(
    docsCollection({
      base: "changelog",
      schemaFields: {
        // `date` drives the reverse-chron sort + timeline marker.
        date: z.coerce.date({
          error: (iss) =>
            iss.input === undefined
              ? 'Missing required "date" in changelog frontmatter (e.g. 2026-06-16).'
              : '"date" must be a valid date (e.g. 2026-06-16).',
        }),
        // Opaque strings — the feed's filter derives its options from them.
        tags: z.array(z.string()).default([]),
      },
    }),
  ),
  partials: defineCollection(partialsCollection()),
};
