/**
 * Regenerate the Bot icon asset module from the source artwork.
 *
 * The client bundle is a single file (`packages/client/lib/client.js`), so the
 * DeepSeekBot mascot artwork ships as base64 data URIs rather than as separate
 * files. Edit the PNGs under `packages/client/assets/bot/` and run
 * `pnpm bot:icons`; never hand-edit the generated module.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const assets = join(root, 'packages/client/assets/bot');
const target = join(root, 'packages/client/src/client/bot-icon-assets.ts');

const sources = [
  ['DEEPSEEKBOT_LIGHT_DATA_URI', 'deepseekbot-light.png'],
  ['DEEPSEEKBOT_DARK_DATA_URI', 'deepseekbot-dark.png'],
];

const lines = [
  '/**',
  ' * DeepSeekBot mascot artwork as data URIs, generated by `pnpm bot:icons`.',
  ' * Do not edit by hand: the source PNGs live in `packages/client/assets/bot/`.',
  ' */',
  '',
];

for (const [name, file] of sources) {
  const bytes = readFileSync(join(assets, file));
  lines.push(`/** \`${file}\` (${String(bytes.byteLength)} bytes) as a PNG data URI. */`);
  lines.push(`export const ${name} = 'data:image/png;base64,${bytes.toString('base64')}';`);
  lines.push('');
}

writeFileSync(target, `${lines.join('\n')}`);
console.log(`bot icons: wrote ${target} (${sources.length} assets)`);
