import type { PersonaBotToolActivity } from '../state/tool-activity.js';

/** A cell of a 32×32 pixel Avatar frame. */
export interface PixelCell {
  x: number;
  y: number;
  c: string;
}

/**
 * Pixel symbols shown in place of a pixel-family face while the PersonaBot works. Each is a 24×24
 * mask (A = body, H = inner detail) centred on the 32 grid and drawn in the Avatar's hair colour.
 */
const SYMBOLS = {
  thinking: [
    '........................',
    '........................',
    '........................',
    '...........AAAA.........',
    '..........AAAAAA........',
    '.........AAAAAAAA.......',
    '.......AAAAAAAAAAA......',
    '.....AAAAAAAAAAAAA......',
    '....AAAAAAAAAAAAAAAA....',
    '....AAAAAAAAAAAAAAAAA...',
    '...AAAAAAAAAAAAAAAAAAA..',
    '...AAAAHHAAAHHAAAHHAAA..',
    '....AAAHHAAAHHAAAHHAAA..',
    '....AAAAAAAAAAAAAAAAAA..',
    '.....AAAAAAAAAAAAAAAA...',
    '.....AAAAAAAAAAAAAAA....',
    '.......AAAAAAAAAAA......',
    '........................',
    '....AA..................',
    '...AAAA.................',
    '...AAAA.................',
    '..A.AA..................',
    '.AAA....................',
    '..A.....................',
  ],
  ask: [
    '........................',
    '........................',
    '...........AAA..........',
    '........AAAAAAAA........',
    '.......AAAAAAAAAA.......',
    '.......AAAAAAAAAA.......',
    '......AAAAA...AAAA......',
    '......AAAA....AAAA......',
    '......AAA.....AAAA......',
    '......AAA.....AAAA......',
    '..............AAAA......',
    '.............AAAAA......',
    '............AAAAA.......',
    '...........AAAAA........',
    '...........AAA..........',
    '..........AAAA..........',
    '..........AAAA..........',
    '...........AA...........',
    '........................',
    '..........AAAA..........',
    '..........AAAA..........',
    '..........AAAA..........',
    '...........AA...........',
    '........................',
  ],
  read: [
    '........................',
    '........................',
    '........................',
    '........................',
    '..AAAAAAA......AAAAAAA..',
    '.AAAAAAAAAA..AAAAAAAAAA.',
    '.AAAAAAAAAAAAAAAAAAAAAA.',
    '.AAAAAAAAAAAAAAAAAAAAAA.',
    '.AAAHHHHHAAAAAAHHHHHAAA.',
    '.AAAHHHHHAAAAAAHHHHHAAA.',
    '.AAAAAAAAAAAAAAAAAAAAAA.',
    '.AAAAAAAAAAAAAAAAAAAAAA.',
    '.AAAHHHHHAAAAAAHHHHHAAA.',
    '.AAAAAAAAAAAAAAAAAAAAAA.',
    '.AAAAAAAAAAAAAAAAAAAAAA.',
    '.AAAAAAAAAAAAAAAAAAAAAA.',
    '.AAAAAAAAAAAAAAAAAAAAAA.',
    '.AAAAAAAAAAAAAAAAAAAAAA.',
    '...........AA...........',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  write: [
    '........................',
    '.....AAAAAAAAAA.........',
    '....AAAAAAAAAAAA........',
    '....AAAAAAAAAAAAA.......',
    '....AAAAAAAAAAAAAA......',
    '....AAAAAAAAAAAAAAA.....',
    '....AAAAAAAAAAAAAAAA....',
    '....AAAAAAAAAAAAAAAA....',
    '....AAAAAAAAAAAAAAAA....',
    '....AAAAAAAHHAAAAAAA....',
    '....AAAAAAAHHAAAAAAA....',
    '....AAAAAAAHHAAAAAAA....',
    '....AAAAAAAHHAAAAAAA....',
    '....AAAHHHHHHHHHHAAA....',
    '....AAAAAAAHHAAAAAAA....',
    '....AAAAAAAHHAAAAAAA....',
    '....AAAAAAAHHAAAAAAA....',
    '....AAAAAAAHHAAAAAAA....',
    '....AAAAAAAAAAAAAAAA....',
    '....AAAAAAAAAAAAAAAA....',
    '....AAAAAAAAAAAAAAAA....',
    '....AAAAAAAAAAAAAAAA....',
    '.....AAAAAAAAAAAAAA.....',
    '........................',
  ],
  edit: [
    '........................',
    '........................',
    '........................',
    '...............AA.......',
    '.............HHAAA......',
    '.............HHHAAA.....',
    '............AAHHHAAA....',
    '...........AAAAHHHAAA...',
    '..........AAAAAAHHHAA...',
    '.........AAAAAAAAHHH....',
    '........AAAAAAAAAAHH....',
    '.......AAAAAAAAAAA......',
    '......AAAAAAAAAAA.......',
    '.....AAAAAAAAAAA........',
    '....AAAAAAAAAAA.........',
    '...AAAAAAAAAAA..........',
    '...AAHHAAAAAA...........',
    '...AAHHHAAAA............',
    '...AAAHHAAA.............',
    '...AAAAAAA..............',
    '...AAAAAA...............',
    '........................',
    '........................',
    '........................',
  ],
  bash: [
    '........................',
    '........................',
    '........................',
    '....AAAAAAAAAAAAAAAA....',
    '..AAAAAAAAAAAAAAAAAAAA..',
    '..AAAAAAAAAAAAAAAAAAAA..',
    '.AAAAAAAAAAAAAAAAAAAAAA.',
    '.AAAAAAAAAAAAAAAAAAAAAA.',
    '.AAAAHHAAAAAAAAAAAAAAAA.',
    '.AAAAHHHAAAAAAAAAAAAAAA.',
    '.AAAAAHHHAAAAAAAAAAAAAA.',
    '.AAAAAAHHHAAAAAAAAAAAAA.',
    '.AAAAAAHHHAAAAAAAAAAAAA.',
    '.AAAAAHHHAAAAAAAAAAAAAA.',
    '.AAAAHHHAAAAAAAAAAAAAAA.',
    '.AAAAHHAAAAHHHHHHHAAAAA.',
    '.AAAAAAAAAAAAAAAAAAAAAA.',
    '.AAAAAAAAAAAAAAAAAAAAAA.',
    '..AAAAAAAAAAAAAAAAAAAA..',
    '..AAAAAAAAAAAAAAAAAAAA..',
    '....AAAAAAAAAAAAAAAA....',
    '........................',
    '........................',
    '........................',
  ],
  search: [
    '........................',
    '........................',
    '.......AAAAAA...........',
    '......AAAAAAAA..........',
    '....AAAAAAAAAAAA........',
    '....AAAAAAAAAAAA........',
    '...AAAA......AAAA.......',
    '..AAAA........AAAA......',
    '..AAAA........AAAA......',
    '..AAAA........AAAA......',
    '..AAAA........AAAA......',
    '..AAAA........AAAA......',
    '..AAAA........AAAA......',
    '...AAAA......AAAA.......',
    '....AAAAAAAAAAAAA.......',
    '....AAAAAAAAAAAAAA......',
    '......AAAAAAAAAAAAA.....',
    '.......AAAAAA..AAAAA....',
    '................AAAAA...',
    '.................AAAAA..',
    '..................AAAAA.',
    '...................AAAA.',
    '....................AA..',
    '........................',
  ],
  web: [
    '........................',
    '........................',
    '.........AHHHHA.........',
    '.......AAHHHHHHAA.......',
    '.....AAAAHHAAHHAAAA.....',
    '....AAAAHHAAAAHHAAAA....',
    '....HHHHHHHHHHHHHHHH....',
    '...AHHHHHHHHHHHHHHHHA...',
    '...AAAAAHAAAAAAHAAAAA...',
    '..AAAAAHHAAAAAAHAAAAAA..',
    '..AAAAAHHAAAAAAHHAAAAA..',
    '..HHHHHHHHHHHHHHHHHHHH..',
    '..HHHHHHHHHHHHHHHHHHHH..',
    '..AAAAAHHAAAAAAHHAAAAA..',
    '..AAAAAHHAAAAAAHAAAAAA..',
    '...AAAAAHAAAAAAHAAAAA...',
    '...AHHHHHHHHHHHHHHHHA...',
    '....HHHHHHHHHHHHHHHH....',
    '....AAAAHHAAAAHHAAAA....',
    '.....AAAAHHAAHHAAAA.....',
    '.......AAHHHHHHAA.......',
    '.........AHHHHA.........',
    '........................',
    '........................',
  ],
  fetch: [
    '........................',
    '..........AAA...........',
    '..........AAAA..........',
    '..........AAAA..........',
    '..........AAAA..........',
    '..........AAAA..........',
    '..........AAAA..........',
    '.....AA...AAAA...AA.....',
    '....AAAA..AAAA..AAAA....',
    '....AAAAA.AAAA.AAAAA....',
    '.....AAAAAAAAAAAAAA.....',
    '......AAAAAAAAAAAA......',
    '.......AAAAAAAAAA.......',
    '........AAAAAAAA........',
    '.........AAAAAA.........',
    '..AAA.....AAAA.....AAA..',
    '..AAA......AA......AAA..',
    '..AAA..............AAA..',
    '..AAA..............AAA..',
    '..AAAAAAAAAAAAAAAAAAAA..',
    '..AAAAAAAAAAAAAAAAAAAA..',
    '..AAAAAAAAAAAAAAAAAAAA..',
    '...AAAAAAAAAAAAAAAAAA...',
    '........................',
  ],
  todo: [
    '........................',
    '........................',
    '....AAAAAAAAAAAAAAAA....',
    '....AAAAAAAAAAAAAAAA....',
    '...AAAAAAAAAAAAAAAAAA...',
    '...AAAAAAAAAAAAAAAAAA...',
    '...AAAAAAAAHAAAAAAAAA...',
    '...AAAAAAAHHAAAAAAAAA...',
    '...AAAHHAHHAAHHHHHAAA...',
    '...AAAAHHHAAAHHHHHAAA...',
    '...AAAAAHAAAAAAAAAAAA...',
    '...AAAAAAAAAAAAAAAAAA...',
    '...AAAAAAAAAAAAAAAAAA...',
    '...AAAAAAAAHAAAAAAAAA...',
    '...AAAAAAAHHAAAAAAAAA...',
    '...AAAHHAHHAAHHHHHAAA...',
    '...AAAAHHHAAAHHHHHAAA...',
    '...AAAAAHAAAAAAAAAAAA...',
    '...AAAAAAAAAAAAAAAAAA...',
    '...AAAAAAAAAAAAAAAAAA...',
    '...AAAAAAAAAAAAAAAAAA...',
    '....AAAAAAAAAAAAAAAA....',
    '.....AAAAAAAAAAAAAA.....',
    '........................',
  ],
  subagent: [
    '........................',
    '........................',
    '........................',
    '........................',
    '.....AAAA......AAAA.....',
    '....AAAAAA....AAAAAA....',
    '....AAAAAAA..AAAAAAA....',
    '....AAAAAAA..AAAAAAA....',
    '....AAAAAAA..AAAAAAA....',
    '....AAAAAA...AAAAAAA....',
    '.....AAAAA....AAAAA.....',
    '........................',
    '........................',
    '........................',
    '.......A................',
    '....AAAAAAA..AAAAAAA....',
    '...AAAAAAAAAAAAAAAAAA...',
    '..AAAAAAAAAAAAAAAAAAAA..',
    '.AAAAAAAAAAAAAAAAAAAAAA.',
    '.AAAAAAAAAAAAAAAAAAAAAA.',
    '.AAAAAAAAAAAAAAAAAAAAAA.',
    '........................',
    '........................',
    '........................',
  ],
  workflow: [
    '........................',
    '........................',
    '........................',
    '..AAAAAA.........AAAAA..',
    '..AAAAAA........AAAAAAA.',
    '.AAAAAAAAAAAAAAAAAAAAAA.',
    '.AAAAAAAAAAAAAAAAAAAAAA.',
    '.AAAAAAAAAAAAAAAAAAAAAA.',
    '.AAAAAAA....AAA.AAAAAAA.',
    '..AAAAAA....AAA..AAAAA..',
    '............AAA.........',
    '............AAA.........',
    '............AAA.........',
    '............AAA.........',
    '............AAA..AAAAA..',
    '............AAA.AAAAAAA.',
    '.............AAAAAAAAAA.',
    '.............AAAAAAAAAA.',
    '...............AAAAAAAA.',
    '................AAAAAAA.',
    '.................AAAAA..',
    '........................',
    '........................',
    '........................',
  ],
  goal: [
    '........................',
    '....AA..................',
    '...AAAA.................',
    '...AAAAAAAAAAAAAAAAA....',
    '...AAAAAAAAAAAAAAAA.....',
    '...AAAAAAAAAAAAAAA......',
    '...AAAAAAAAAAAAAAA......',
    '...AAAAAAAAAAAAAA.......',
    '...AAAAAAAAAAAAAA.......',
    '...AAAAAAAAAAAAAAA......',
    '...AAAAAAAAAAAAAAAA.....',
    '...AAAAAAAAAAAAAAAAA....',
    '...AAAA.................',
    '...AAAA.................',
    '...AAAA.................',
    '...AAAA.................',
    '...AAAA.................',
    '...AAAA.................',
    '...AAAA.................',
    '...AAAA.................',
    '...AAAA.................',
    '...AAAA.................',
    '...AAAA.................',
    '....AA..................',
  ],
  present: [
    '........................',
    '........................',
    '...AAAAAAAAAAAAAAAAAA...',
    '..AAAAAAAAAAAAAAAAAAAA..',
    '.AAAAAAAAAAAAAAAAAAAAAA.',
    '.AAAAAAAAAAAAAAAAAHAAAA.',
    '.AAAAAAAAAAAAAAAAAHAAAA.',
    '.AAAAAAAAAHAAAAAAAHAAAA.',
    '.AAAAAAAAAHAAAHAAAHAAAA.',
    '.AAAAAHAAAHAAAHAAAHAAAA.',
    '.AAAAAHAAAHAAAHAAAHAAAA.',
    '.AAAAAHAAAHAAAHAAAHAAAA.',
    '.AAAAAHAAAHAAAHAAAHAAAA.',
    '.AAAAAHAAAHAAAHAAAHAAAA.',
    '.AAAAAAAAAAAAAAAAAAAAAA.',
    '..AAAAAAAAAAAAAAAAAAAA..',
    '...AAAAAAAAAAAAAAAAAA...',
    '.........AAAAAA.........',
    '........AAAAAAAA........',
    '........AAA..AAA........',
    '.......AAA....AAA.......',
    '.......AAA....AAA.......',
    '.......AA......AA.......',
    '........................',
  ],
  approval: [
    '........................',
    '........................',
    '.........AAAAAA.........',
    '......AAAAAAAAAAAA......',
    '....AAAAAAAAAAAAAAAA....',
    '...AAAAAAAAHHAAAAAAAA...',
    '...AAAAAAAAHHAAAAAAAA...',
    '...AAAAAAAAHHAAAAAAAA...',
    '...AAAAAAAAHHAAAAAAAA...',
    '...AAAAAAAAHHAAAAAAAA...',
    '...AAAAAAAAHHAAAAAAAA...',
    '...AAAAAAAAHHAAAAAAAA...',
    '...AAAAAAAAHHAAAAAAAA...',
    '....AAAAAAAHHAAAAAAA....',
    '....AAAAAAAAAAAAAAAA....',
    '....AAAAAAAAAAAAAAAA....',
    '.....AAAAAAHHAAAAAA.....',
    '.....AAAAAAHHAAAAAA.....',
    '......AAAAAAAAAAAA......',
    '.......AAAAAAAAAA.......',
    '........AAAAAAAA........',
    '.........AAAAA..........',
    '...........AA...........',
    '........................',
  ],
  other: [
    '........................',
    '........................',
    '........................',
    '...........AA...........',
    '...........AA...........',
    '..........AAAA..........',
    '..........AAAA..........',
    '..........AAAA..........',
    '.........AAAAAA.........',
    '........AAAAAAAA........',
    '.....AAAAAAAAAAAAAA.....',
    '...AAAAAAAAAAAAAAAAAA...',
    '...AAAAAAAAAAAAAAAAAA...',
    '.....AAAAAAAAAAAAAA.....',
    '........AAAAAAAA........',
    '.........AAAAAA.........',
    '..........AAAA..........',
    '..........AAAA..........',
    '..........AAAA..........',
    '...........AA...........',
    '...........AA...........',
    '........................',
    '........................',
    '........................',
  ],
} as const satisfies Record<string, readonly string[]>;

export type PixelSymbol = keyof typeof SYMBOLS;
export const PIXEL_SYMBOLS = Object.keys(SYMBOLS) as PixelSymbol[];

const BY_TOOL_NAME: Record<string, PixelSymbol> = {
  ask_user_question: 'ask',
  read: 'read',
  read_image: 'read',
  skill: 'read',
  write: 'write',
  edit: 'edit',
  str_replace_editor: 'edit',
  bash: 'bash',
  pwsh: 'bash',
  job_kill: 'bash',
  job_list: 'bash',
  job_output: 'bash',
  grep: 'search',
  glob: 'search',
  web_search: 'web',
  web_fetch: 'fetch',
  todo_write: 'todo',
  subagent: 'subagent',
  list_subagent_models: 'subagent',
  workflow: 'workflow',
  create_goal: 'goal',
  get_goal: 'goal',
  update_goal: 'goal',
  present: 'present',
};

const BY_TOOL_KIND: Record<string, PixelSymbol> = {
  read: 'read',
  edit: 'edit',
  delete: 'edit',
  move: 'edit',
  search: 'search',
  fetch: 'fetch',
  execute: 'bash',
};

/** The symbol for a presentation, or undefined when the face should show. */
export function pixelSymbolFor(
  state: string,
  activity: Pick<PersonaBotToolActivity, 'toolName' | 'toolKind'> | undefined,
  approvals: number,
): PixelSymbol | undefined {
  if (approvals > 0 && (state === 'working' || state === 'waiting')) return 'approval';
  if (state === 'thinking') return 'thinking';
  if (state !== 'working') return undefined;
  const name = activity?.toolName;
  if (name !== undefined && Object.hasOwn(BY_TOOL_NAME, name)) return BY_TOOL_NAME[name];
  const kind = activity?.toolKind;
  if (kind !== undefined && Object.hasOwn(BY_TOOL_KIND, kind)) return BY_TOOL_KIND[kind];
  return 'other';
}

const INK = '#2a2230';
const channels = (color: string) => {
  const n = Number.parseInt(color.slice(1), 16);
  return [16, 8, 0].map((bit) => (n >> bit) & 255);
};
const mix = (base: string, tint: string, k: number) => {
  const t = channels(tint);
  return `#${channels(base)
    .map((v, i) =>
      Math.round(v * (1 - k) + t[i]! * k)
        .toString(16)
        .padStart(2, '0'),
    )
    .join('')}`;
};

/** The symbol's cells on the 32 grid, in the given colour with a highlight, a shaded edge and an ink outline. */
export function pixelSymbolCells(symbol: PixelSymbol, color: string): PixelCell[] {
  const rows = SYMBOLS[symbol];
  const body = new Map<string, 'A' | 'H'>();
  rows.forEach((row, y) =>
    [...row].forEach((code, x) => {
      if (code === 'A' || code === 'H') body.set(`${x + 4},${y + 4}`, code);
    }),
  );
  const light = mix(color, '#ffffff', 0.75);
  const low = mix(color, INK, 0.25);
  const cells: PixelCell[] = [];
  for (const [key, code] of body) {
    const [x, y] = key.split(',').map(Number) as [number, number];
    const edge = x + y > 34 && !body.has(`${x + 1},${y + 1}`);
    cells.push({ x, y, c: code === 'H' ? light : edge ? low : color });
  }
  const outline = new Set<string>();
  for (const key of body.keys()) {
    const [x, y] = key.split(',').map(Number) as [number, number];
    for (const [dx, dy] of [
      [1, 0],
      [-1, 0],
      [0, 1],
      [0, -1],
    ] as const) {
      const next = `${x + dx},${y + dy}`;
      if (body.has(next) || outline.has(next)) continue;
      outline.add(next);
      cells.push({ x: x + dx, y: y + dy, c: INK });
    }
  }
  return cells;
}
